### ISSUE TITLE
Mobile version button has a tail

### ISSUE THREAD

**Issue by vidiecan** [ufal/lindat-common#23]
![image](https://cloud.githubusercontent.com/assets/332350/10220383/666ae1d4-6847-11e5-984f-3efd19619624.png)

**Comment by m1ch4ls** [comment]
I assume this is screenshot from https://lindat.mff.cuni.cz/en - the page uses the old lindat-common.

The issue is causes by `&nbsp;` in `<span class="icon-bar">&nbsp;</span>`
Adding this can fix the issue:
```.css
.navbar-toggle .icon-bar {
    display: block;
    width: 22px;
    height: 2px;
    border-radius: 1px;
    line-height: 0;
    font-size: 0;
}
```

But the more important question: @kosarko what is blocking deployment of the new lindat-common? Can I help in any way?

**Comment by m1ch4ls** [comment]
No longer an issue
